spring.application.name=student-management-api
spring.datasource.url=jdbc:postgresql://localhost:5332/lazardb
spring.datasource.username=lazar
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.data.web.pageable.default-page-size=5
spring.data.web.pageable.max-page-size=50

jwt.secret=yourVerySecretKeyYourVerySecretKey123456
jwt.expiration=86400000
jwt.refresh-expiration=604800000