-- 1. Kreiranje tabele za Departmane/Smerove
CREATE TABLE departments (
                             id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             code VARCHAR(50) UNIQUE NOT NULL,
                             name VARCHAR(100) NOT NULL,
                             created_at TIMESTAMP NOT NULL,
                             updated_at TIMESTAMP,
                             deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- 2. Kreiranje tabele za Studente
CREATE TABLE students (
                          id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(100) NOT NULL,
                          email VARCHAR(100) UNIQUE NOT NULL,
                          age INT NOT NULL,
                          status VARCHAR(50) NOT NULL,
                          enrollment_date DATE,
                          graduation_date DATE,
                          department_id INT,
                          created_at TIMESTAMP NOT NULL,
                          updated_at TIMESTAMP,
                          deleted BOOLEAN NOT NULL DEFAULT FALSE,
                          CONSTRAINT fk_student_department FOREIGN KEY (department_id) REFERENCES departments(id)
);

-- 3. Kreiranje tabele za Kurseve/Predmete
CREATE TABLE courses (
                         id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         code VARCHAR(50) UNIQUE NOT NULL,
                         name VARCHAR(100) NOT NULL,
                         credits INT NOT NULL,
                         max_students INT NOT NULL,
                         department_id INT,
                         created_at TIMESTAMP NOT NULL,
                         updated_at TIMESTAMP,
                         deleted BOOLEAN NOT NULL DEFAULT FALSE,
                         CONSTRAINT fk_course_department FOREIGN KEY (department_id) REFERENCES departments(id)
);

-- 4. Spojna tabela za Many-to-Many vezu između Studenata i Kurseva
CREATE TABLE student_courses (
                                 student_id INT NOT NULL,
                                 course_id INT NOT NULL,
                                 PRIMARY KEY (student_id, course_id),
                                 CONSTRAINT fk_sc_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
                                 CONSTRAINT fk_sc_course FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE
);

-- 5. Kreiranje tabele za Korisnike (Auth sistem)
CREATE TABLE users (
                       id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(100) NOT NULL,
                       email VARCHAR(100) UNIQUE NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       role VARCHAR(50) NOT NULL
);

-- 6. Kreiranje tabele za Refresh Tokene
CREATE TABLE refresh_tokens (
                                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                token VARCHAR(255) UNIQUE NOT NULL,
                                expiration_date TIMESTAMP NOT NULL,
                                revoked BOOLEAN NOT NULL DEFAULT FALSE,
                                users_id INT NOT NULL, -- <-- PROMENJENO SA user_id NA users_id
                                CONSTRAINT fk_token_user FOREIGN KEY (users_id) REFERENCES users(id) ON DELETE CASCADE
);